name: Lint

on:
  pull_request_target:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node

      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          fail_on_error: true
          eslint_flags: "--cache --report-unused-disable-directives \"**/*.{js,jsx,ts,tsx,cjs,mjs,vue}\""

  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node

      - name: Run stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          fail_on_error: true
          stylelint_input: "\"**/*.{css,scss}\""
