name: Lint

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node

      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: "--cache --report-unused-disable-directives \"**/*.{js,jsx,ts,tsx,cjs,mjs,vue}\""

  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node

      - name: Run stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          stylelint_input: "\"**/*.{css,scss}\""
